import { AuthProvider } from "@/config/contexts/AuthContext";
import { Toaster } from "sonner";
import '@/styles/globals.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <Toaster
            position="top-right"
            richColors
            theme="dark"
          />
        </AuthProvider>
      </body>
    </html>
  );
}
